apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wanderlust-ns
  labels:
    app: wanderlust-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wanderlust-backend
  template:
    metadata:
      labels:
        app: wanderlust-backend
    spec:
      containers:
        - name: backend
          image: roshanx/wanderlust-backend:latest # Replace with your registry image
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PORT
              value: "8080"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: DB_HOST
              value: "mongodb"
            - name: DB_PORT
              value: "27017"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wanderlust-secrets
                  key: db-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wanderlust-secrets
                  key: db-pass
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wanderlust-secrets
                  key: jwt-secret
