pipeline {
    agent any

    parameters {
        string(name: 'FRONTEND_TAG', description: 'Frontend Docker Image Tag', defaultValue: 'latest')
        string(name: 'BACKEND_TAG', description: 'Backend Docker Image Tag', defaultValue: 'latest')
    }

    environment {
        GITHUB_CREDENTIALS = 'Github-cred'
        GITHUB_REPO = 'https://github.com/Roshanx96/Wanderlust-Mega-Project.git'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', credentialsId: "${env.GITHUB_CREDENTIALS}", url: "${env.GITHUB_REPO}"
            }
        }

        stage('Verify: Docker Image Tags') {
            steps {
                script {
                    echo "FRONTEND_TAG: ${params.FRONTEND_TAG}"
                    echo "BACKEND_TAG: ${params.BACKEND_TAG}"
                }
            }
        }

        stage("Update: Kubernetes manifests") {
            steps {
                dir('kubernetes') {
                    sh """
                        echo "Updating backend image tag..."
                        sed -i -E 's|(wanderlust-backend-beta:).*|\\1${params.BACKEND_TAG}|' backend.yaml

                        echo "Updating frontend image tag..."
                        sed -i -E 's|(wanderlust-frontend-beta:).*|\\1${params.FRONTEND_TAG}|' frontend.yaml
                    """
                }
            }
        }

        stage("Git: Code update and push to GitHub") {
            steps {
                dir('kubernetes') {
                    script {
                        withCredentials([gitUsernamePassword(credentialsId: 'Github-cred', gitToolName: 'Default')]) {
                            sh '''
                                echo "Checking repository status:"
                                git status

                                echo "Adding changes to Git:"
                                git add .

                                echo "Committing changes (if any):"
                                git commit -m "Updated image tags in Kubernetes manifests" || echo "⚠️ No changes to commit."

                                echo "Pushing changes to GitHub:"
                                git push https://github.com/Roshanx96/Wanderlust-Mega-Project.git main
                            '''
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo "✅ Wanderlust CD Pipeline Successful"
        }
        failure {
            echo "❌ Wanderlust CD Pipeline Failed"
        }
    }
}
